### ISSUE TITLE
`go get` can only get V4 

### ISSUE THREAD

**Issue by futurechallenger** [graph-gophers/dataloader#42]
`go get` command can only get V4 package, not V5.
But this can help: `go get -u gopkg.in/nicksrandall/dataloader.v5`, then
```go
import "gopkg.in/nicksrandall/dataloader.v5"
```

**Comment by pugovok** [comment]
+1
need set correct tag version. v5.1.0

**Comment by tonyghita** [comment]
I've cut the v5 release with semantic versioning https://github.com/graph-gophers/dataloader/releases/tag/v5.0.0
