### ISSUE TITLE
Semantic Versioning tag

### ISSUE THREAD

**Issue by pugovok** [graph-gophers/dataloader#45]
Please set semver actual tag:
Correct actual version: v5.0.0
current version v5 not valid for modules

**Comment by jdeal-mediamath** [comment]
Yes please! This make importing via go modules impossible.

**Comment by pugovok** [comment]
ping @nicksrandall

**Comment by nicksrandall** [comment]
Sorry I missed this! I will do this later today.

**Comment by tonyghita** [comment]
Let us know if this works for you:  https://github.com/graph-gophers/dataloader/releases/tag/v5.0.0

**Comment by pugovok** [comment]
Thanks a lot
