### ISSUE TITLE
Duplicate key for batchFun when applying no cache

### ISSUE THREAD

**Issue by KingWu** [graph-gophers/dataloader#68]
When applying no cache policy, i found that duplicate keys passed to batchFuc. 
After i query the keys from database and return the results, then will throw error which tell you the size of result and keys is not matched.

**Comment by nicksrandall** [comment]
No cache policy does no caching (and therefore no deduping). I think you'll have to handle the duplicate keys yourself if you intend to use that policy. 

Generally speaking, the no-cache policy is intended for use-cases where there never would be any duplicates.
