### ISSUE TITLE
Keys passed to batchFn can be sort by asc?

### ISSUE THREAD

**Issue by KingWu** [graph-gophers/dataloader#69]
Any way to sort the `Keys` passed to `batchFn`?

**Comment by nicksrandall** [comment]
You could sort the keys as the first step in your batch function if you need them sorted. An easy way to accomplish this would be to have your key interface also implement the `sort.Interface` interface so that you could sort the keys using the std lib.

**Comment by pavelnikolov** [comment]
This is not directly related to the library's functionality. @nicksrandall's solution seems good.
