### ISSUE TITLE
Passing query information to batch function? 

### ISSUE THREAD

**Issue by dancarlocanlas** [graph-gophers/dataloader#70]
Is it possible to pass on the query information (specifically the fields requested) to the batch loader function? With my current implementation, the creation of the loader is done outside of the resolver (like other samples) and there is no way to pass the query information to the batch function from within the resolver function.

**Comment by nicksrandall** [comment]
Yes, you *could* do this but the exercise is left to the user. This is primary the reason we use interfaces as keys and not raw strings. This way, you can embed all the information you want in the key and then use that as part of your batch function.

**Comment by dancarlocanlas** [comment]
@nicksrandall got it. Was able to implement a way around this. Thanks!
