### ISSUE TITLE
Add generic support on next release?

### ISSUE THREAD

**Issue by tsh96** [graph-gophers/dataloader#83]
Go will add generic feature on next release(1.18).
This feature can bring a significant benefit like static type checking for user.

**Comment by frederikhors** [comment]
I would really like! And it would also be useful code to learn how to use the new generics!

**Comment by errorhandler** [comment]
As part of my own learning around generics I've created a [fork](https://github.com/errorhandler/dataloader) that is all generics based, for those interested.

**Comment by pavelnikolov** [comment]
https://github.com/graph-gophers/dataloader/pull/84

**Comment by csilvers** [comment]
(I don't have the necessary permissions, but I think this can be closed now.)
