### ISSUE TITLE
how to use redis as cache

### ISSUE THREAD

**Issue by ffrankfeng** [graph-gophers/dataloader#91]

**Comment by eaglemoor** [comment]
U need to support dataloader.Cache interface.

**Comment by rwrz** [comment]
Isn't that easy. The cache interface returns a Thunk[V], which is like a "callback function". It is not possible to "encode" and save it on Redis. 
Based on this answer here, I was expecting it to be possible, but I just realize now that it won't be possible.
-
Is there a way to refactor the loader to save/load values and not functions?

**Comment by eaglemoor** [comment]
@rwrz u can use Redis cache in batch function, without cache in dataloader
